
const book = 'https://app.bluenotary.us/business/register?referralCode=5ujkkgs0s';
const services=['Power of Attorney','Trusts & Wills','Vehicle Title Transfers','Real Estate Documents','Business Documents','Medical Authorization','School Forms','Affidavits','Lease Agreements'];
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Dallas-Fort Worth Mobile Notary • Texas Online Notary</div><h1>Notary service that meets you where you are.</h1><p className="lead">AMNS TX provides mobile notary appointments across the DFW Metroplex and secure remote online notarization statewide across Texas.</p><div className="actions"><a className="btn" href={book}>Book Online</a><a className="btn secondary" href="sms:4692155434">Text Now</a><a className="btn light" href="tel:2144715358">Call Now</a></div><div className="trust-row"><div className="trust">Texas Commissioned</div><div className="trust">Bonded & Insured</div><div className="trust">Mobile + Online</div><div className="trust">Same-Day Options</div></div></div><div className="card"><span className="tag">Book in 3 Steps</span><h3>Simple, fast, and professional.</h3><ul className="feature-list"><li>Choose mobile or online service</li><li>Confirm your ID and document needs</li><li>Book your appointment and pay by card</li></ul><p className="mini">Questions? Text 469-215-5434 before booking.</p></div></div></section>
<section className="section"><div className="container"><h2>Most Requested Services</h2><p>Choose the service that fits your document, then book online or text for a quote.</p><div className="grid three">{services.map(s=><div className="card service-card" key={s}><span className="tag">Notary Service</span><h3>{s}</h3><p>Professional notarization support for common personal, business, medical, school, and real estate documents.</p><a className="btn secondary" href={book}>Book This Service</a></div>)}</div></div></section>
<section className="section soft"><div className="container grid two"><div><h2>Why Choose AMNS TX?</h2><ul className="feature-list"><li>Mobile appointments at homes, offices, hospitals, and public meeting locations</li><li>Remote online notary available statewide across Texas</li><li>Clear pricing before your appointment</li><li>Professional communication and appointment confirmations</li><li>Business and recurring client options available</li></ul></div><div className="card"><h3>Meet Avery Burgin</h3><p>AMNS TX is owned by Avery Burgin, a Texas commissioned notary public focused on convenient, professional, and reliable notarization services across Dallas-Fort Worth and online throughout Texas.</p><p className="mini">Add your professional headshot here for stronger trust and higher conversion.</p></div></div></section>
<section className="section"><div className="container"><div className="cta-band"><div><h2>Need a notary today?</h2><p>Book online, call, or text with your document type, number of signers, and location.</p></div><a className="btn secondary" href={book}>Start Booking</a></div></div></section>
</>}
