
"use client";
import { useMemo, useState } from "react";
const states=["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"];
export default function AcceptedIdChecker(){
 const [idType,setIdType]=useState("driver-license"); const [state,setState]=useState("Texas"); const [valid,setValid]=useState("valid"); const [witness,setWitness]=useState("no"); const [witnessId,setWitnessId]=useState("yes"); const [knows,setKnows]=useState("yes"); const [benefit,setBenefit]=useState("no");
 const result=useMemo(()=>{if(valid==="valid")return{tone:"ok",title:"Likely acceptable ID",message:"A current, government-issued ID may be acceptable when it includes the required identifying information and the signer personally appears before the notary."}; if(valid==="unsure")return{tone:"warn",title:"Check before booking",message:"If you are not sure whether your ID is valid, contact us before scheduling so we can help avoid a wasted appointment."}; if(valid==="expired"&&witness==="no")return{tone:"bad",title:"Expired ID by itself may not be enough",message:"An expired ID may not be used by itself for identification. If you do not have valid ID, a credible witness may be possible when all requirements are met."}; if(valid==="expired"&&witness==="yes"){if(witnessId!=="yes")return{tone:"bad",title:"Witness needs valid ID",message:"A credible witness must be able to prove their own identity with valid identification."}; if(knows!=="yes")return{tone:"bad",title:"Witness must personally know the signer",message:"A credible witness must personally know the signer and be able to swear or affirm to the signer’s identity."}; if(benefit!=="no")return{tone:"bad",title:"Witness cannot benefit from the document",message:"A credible witness should not have a financial or personal interest in the document being notarized."}; return{tone:"warn",title:"Credible witness may be possible",message:"If the signer does not have valid ID, a credible witness may be possible when the witness personally knows the signer, has valid ID, is present, and has no interest in the document. Final approval depends on the appointment and document."}} return{tone:"warn",title:"Contact us before booking",message:"Identification requirements can vary by appointment type, document, and platform."}},[valid,witness,witnessId,knows,benefit]);
 const cls=result.tone==="bad"?"result id-result-bad":result.tone==="warn"?"result id-result-warn":"result";
 return <div className="tool"><h3>Accepted ID Checker</h3><p>Check your identification before booking. This is general guidance only and does not guarantee notarization.</p><label>ID type</label><select value={idType} onChange={e=>setIdType(e.target.value)}><option value="driver-license">Driver License</option><option value="state-id">State ID</option><option value="passport">U.S. Passport / Passport Card</option><option value="military">Military ID</option><option value="other">Other Government ID</option></select>{(idType==="driver-license"||idType==="state-id")&&<><label>State that issued the ID</label><select value={state} onChange={e=>setState(e.target.value)}>{states.map(s=><option key={s} value={s}>{s}</option>)}</select></>}<label>Is the ID current and unexpired?</label><select value={valid} onChange={e=>setValid(e.target.value)}><option value="valid">Yes, it is current and unexpired</option><option value="expired">No, it is expired</option><option value="unsure">I am not sure</option></select>{valid==="expired"&&<><label>Do you have a credible witness with you?</label><select value={witness} onChange={e=>setWitness(e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select>{witness==="yes"&&<><label>Does the witness have valid ID?</label><select value={witnessId} onChange={e=>setWitnessId(e.target.value)}><option value="yes">Yes</option><option value="no">No</option></select><label>Does the witness personally know the signer?</label><select value={knows} onChange={e=>setKnows(e.target.value)}><option value="yes">Yes</option><option value="no">No</option></select><label>Does the witness benefit from the document?</label><select value={benefit} onChange={e=>setBenefit(e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select></>}</>}<div className={cls}><strong>{result.title}</strong><br/>{result.message}</div><p className="small" style={{marginTop:"14px"}}>A Mobile Notary Service cannot give legal advice. The signer must personally appear and sign willingly.</p></div>
}
