
import NotaryChecker from "./NotaryChecker";
import QuoteCalculator from "./QuoteCalculator";
const bookingLink="https://app.bluenotary.us/business/register?referralCode=5ujkkgs0s";
export function Hero(){
 return <section className="hero"><div className="container hero-grid"><div><div className="badge">Same-day appointments available</div><h1>Mobile & Online Notary Services Across Texas.</h1><p className="hero-text">Professional notarization for Dallas-Fort Worth clients in person, plus secure remote online notary appointments statewide.</p><div className="hero-actions"><a className="btn btn-primary" href="tel:+12144715358">Call Now</a><a className="btn btn-secondary" href={bookingLink}>Book Appointment</a></div><div className="trust-grid"><div><span className="check">✓</span>Texas Commissioned Notary</div><div><span className="check">✓</span>Bonded & Insured</div><div><span className="check">✓</span>DFW Mobile Service</div><div><span className="check">✓</span>Remote Online Notary</div></div></div><div className="step-card"><div className="step-inner"><p className="eyebrow">Book in 3 steps</p>{[["1","Tell us your document type","Affidavit, power of attorney, vehicle form, school form, business form, or another notarizable document."],["2","Choose Mobile or Online","We travel across DFW or meet you online through a secure remote online notary platform."],["3","Bring valid ID","Signer must personally appear, understand the document, be willing to sign, and present acceptable identification."]].map(([n,t,b])=><div className="step" key={n}><div className="num">{n}</div><div><h3>{t}</h3><p>{b}</p></div></div>)}</div></div></div></section>
}
export function ServicesCards(){
 const cards=[["Mobile Notary","We travel to homes, apartments, offices, hospitals, nursing facilities, and approved public meeting locations across DFW."],["Online Notary","Remote online notarization for eligible Texas documents through a secure video session and identity verification."],["Traditional Notary","Standard notarizations for common documents including affidavits, acknowledgments, jurats, statements, and business forms."]];
 return <section className="section" id="services"><div className="container"><div className="section-head"><p className="eyebrow">Services</p><h2>Notary services</h2><p>Choose the appointment type that fits your document, location, and schedule.</p></div><div className="grid-3">{cards.map(([t,b])=><div className="card" key={t}><div className="icon">✓</div><h3>{t}</h3><p>{b}</p></div>)}</div></div></section>
}
export function WhyChoose(){
 const items=[["Professional, clear process","The site explains what to bring, how booking works, and what to expect before the appointment."],["Built for busy clients","Clients can call, text, book online, check documents, and estimate pricing without searching around."],["Mobile plus online options","A Mobile Notary Service can help DFW clients in person and Texas clients online when eligible."],["Designed to reduce delays","Accepted ID, document readiness, add-ons, and policies are explained upfront."]];
 return <section className="section tint"><div className="container split"><div><p className="eyebrow">Why Choose Us</p><h2 style={{fontSize:"43px",letterSpacing:"-.055em",lineHeight:"1.05",margin:"0 0 14px"}}>A notary experience that feels simple, clear, and professional.</h2><p style={{color:"#637084",lineHeight:"1.7"}}>Instead of making clients guess, the website guides them through the process before they book.</p></div><div className="feature-list">{items.map(([t,b])=><div className="feature" key={t}><strong>{t}</strong>{b}</div>)}</div></div></section>
}
export function PricingCards(){
 const cards=[["Traditional Notary","Texas regulated fees","For clients who can meet locally and need standard notarization only.",["First notarized signature: $10","Additional signatures may apply","Valid ID required"]],["Mobile Notary","Travel fee + notary fee","For clients who need us to travel to an approved appointment location.",["Travel starts at an estimated $25","Parking/tolls/wait time may apply","After-hours may be additional"]],["Online Notary","$25 session + $10 signature","For eligible documents notarized online through a secure session.",["Secure online session","Statewide Texas online service","Valid ID and platform approval required"]]];
 return <section className="section white" id="pricing"><div className="container"><div className="section-head"><p className="eyebrow">Pricing</p><h2>Simple pricing</h2><p>Clear pricing helps customers book faster. Final pricing may depend on distance, urgency, document type, and add-on needs.</p></div><div className="grid-3">{cards.map(([t,p,b,bullets])=><div className="card" key={t}><h3>{t}</h3><div className="price">{p}</div><p>{b}</p><div className="list">{bullets.map(x=><div key={x}><span className="check">✓</span>{x}</div>)}</div></div>)}</div></div></section>
}
export function CommonDocuments(){
 const docs=["Power of Attorney","Affidavits","Child Travel Consent","Vehicle Title Forms","Business Documents","Medical Forms","School Forms","Real Estate Documents","Statements & Jurats","Acknowledgments","Apartment Forms","General Forms"];
 return <section className="section"><div className="container"><div className="section-head"><p className="eyebrow">Common Documents</p><h2>Documents clients commonly need notarized.</h2><p>This section helps customers recognize their document type fast and improves search visibility.</p></div><div className="pill-grid">{docs.map(d=><div className="pill" key={d}>✓ {d}</div>)}</div></div></section>
}
export function AddOns(){
 const addOns=["Printing services","Scan backs","Document delivery","Witness coordination when permitted","After-hours appointments","Expedited appointments","Hospital visits","Nursing facility visits","Jail visits","Business appointments","Apartment community appointments","Real estate document support"];
 return <section className="section" id="add-ons"><div className="container"><div className="section-head"><p className="eyebrow">Add-On Services</p><h2>More than a basic stamp.</h2><p>Optional services help make your appointment smoother, faster, and easier to complete.</p></div><div className="pill-grid">{addOns.map(x=><div className="pill" key={x}>✓ {x}</div>)}</div></div></section>
}
export function ToolsSection(){return <section className="section white" id="tools"><div className="container"><div className="section-head"><p className="eyebrow">Helpful Tools</p><h2>Check your document and estimate your price.</h2><p>These tools make the site more useful than a regular notary page and help clients book with confidence.</p></div><div className="tool-wrap"><NotaryChecker/><QuoteCalculator/></div></div></section>}
export function HowItWorks(){
 const steps=[["1","Prepare your document","Make sure all pages are present and blank spaces are completed before the appointment."],["2","Verify signer and ID","The signer must personally appear, understand the document, and present acceptable identification."],["3","Complete notarization","We complete the notarial certificate, apply the stamp/seal where appropriate, and finish the appointment."]];
 return <section className="section tint"><div className="container"><div className="section-head"><p className="eyebrow">How It Works</p><h2>Clear steps from first click to finished notarization.</h2><p>A professional process helps clients feel confident before they call or book.</p></div><div className="grid-3">{steps.map(([n,t,b])=><div className="card" key={n}><div className="num">{n}</div><h3 style={{marginTop:"16px"}}>{t}</h3><p>{b}</p></div>)}</div></div></section>
}
export function AcceptedIdPreview(){
 const ids=["Current driver license or state ID","U.S. passport or passport card","Military ID or approved government ID","Signer must be present and willing","Document should be complete before notarization","Online appointments may require platform ID verification"];
 return <section className="section dark" id="accepted-ids"><div className="container"><div className="section-head"><p className="eyebrow">Accepted IDs</p><h2>Know what to bring before your appointment.</h2><p>Every signer must personally appear and present acceptable identification.</p></div><div className="grid-3">{ids.map(x=><div className="card" key={x}>✓ {x}</div>)}</div></div></section>
}
export function ServiceAreas(){
 const cities=["Dallas","Irving","Fort Worth","Arlington","Plano","Grand Prairie","Mesquite","Garland","Richardson","Duncanville","Carrollton","Farmers Branch"];
 return <section className="section" id="service-areas"><div className="container"><div className="section-head"><p className="eyebrow">Service Areas</p><h2>Mobile notary service across DFW.</h2><p>Service area pages help clients find you when they search for mobile notary service nearby.</p></div><div className="pill-grid">{cities.map(c=><div className="pill" key={c}>Mobile Notary {c}</div>)}</div></div></section>
}
export function FAQBlock(){
 const faqs=[["Can you explain or prepare my document?","No. We are not attorneys and cannot provide legal advice, prepare legal documents, or choose the notarial act for you."],["Do I need valid ID?","Yes. Every signer must personally appear and present acceptable identification."],["Do you offer online notarization?","Yes. Remote online notarization is available for eligible Texas documents through a secure online platform."],["Do you travel?","Yes. Mobile appointments are available across Dallas-Fort Worth. Travel fees may apply."],["Can I book same day?","Same-day availability may be available depending on schedule, location, and document readiness."],["What if my document needs witnesses?","Some documents require witnesses. We can discuss witness coordination where permitted, but you are responsible for knowing document requirements."]];
 return <section className="section white"><div className="container"><div className="section-head"><p className="eyebrow">FAQ</p><h2>Questions before booking</h2><p>Clear answers reduce confusion and help clients book the right service.</p></div><div className="grid-2">{faqs.map(([q,a])=><div className="card" key={q}><h3>{q}</h3><p>{a}</p></div>)}</div></div></section>
}
export function CTA(){return <section className="section"><div className="container"><div className="card" style={{textAlign:"center",padding:"44px"}}><p className="eyebrow">Ready to book?</p><h2 style={{fontSize:"40px",letterSpacing:"-.05em",margin:"0 0 12px"}}>Call now or schedule your appointment online.</h2><p>Serving Dallas-Fort Worth in person and Texas statewide online.</p><div className="hero-actions" style={{justifyContent:"center"}}><a className="btn btn-primary" href="tel:+12144715358">Call Now</a><a className="btn btn-cyan" href={bookingLink}>Book Appointment</a></div></div></div></section>}
