
import NotaryChecker from "./NotaryChecker";
import QuoteCalculator from "./QuoteCalculator";
import AcceptedIdChecker from "./AcceptedIdChecker";
const bookingLink="https://app.bluenotary.us/business/register?referralCode=5ujkkgs0s";

export function Hero(){return <section className="hero"><div className="container hero-grid"><div><div className="badge">Same-day appointments may be available</div><h1>Mobile & Online Notary Services Across Texas.</h1><p className="hero-text">A Mobile Notary Service provides professional, convenient notarization for individuals, families, and businesses. We offer mobile appointments throughout the Dallas-Fort Worth Metroplex and secure online notarization for eligible Texas documents statewide.</p><div className="hero-actions"><a className="btn btn-primary" href="tel:+12144715358">Call Now</a><a className="btn btn-secondary" href={bookingLink}>Book Appointment</a></div><div className="trust-grid"><div><span className="check">✓</span>Texas Commissioned Notary</div><div><span className="check">✓</span>Bonded & Insured</div><div><span className="check">✓</span>DFW Mobile Appointments</div><div><span className="check">✓</span>Statewide Online Notary</div></div></div><div className="step-card"><div className="step-inner"><p className="eyebrow">Book in 3 steps</p><div className="step"><div className="num">1</div><div><h3>Tell us what you need notarized</h3><p>Share the document type, number of signers, appointment location, and whether you need mobile or online service.</p></div></div><div className="step"><div className="num">2</div><div><h3>Confirm ID and appointment details</h3><p>Each signer must personally appear, provide acceptable identification, and be willing to sign.</p></div></div><div className="step"><div className="num">3</div><div><h3>Complete your notarization</h3><p>Once all requirements are met, the notarial act is completed and your appointment is finalized.</p></div></div></div></div></div></section>}

export function ServicesCards(){const cards=[["Mobile Notary","We travel to homes, apartments, offices, hospitals, nursing facilities, and approved public locations across Dallas-Fort Worth. Travel pricing is confirmed before the appointment."],["Online Notary","Remote online notarization is available for eligible Texas documents through a secure platform with identity verification and live video session."],["Traditional Notary","Standard notarizations are available for affidavits, acknowledgments, jurats, statements, business forms, school forms, and more."]];return <section className="section" id="services"><div className="container"><div className="section-head"><p className="eyebrow">Services</p><h2>Notary services made simple.</h2><p>Choose the option that fits your document, location, and schedule. If you are unsure, call before booking and we’ll help you understand your options without providing legal advice.</p></div><div className="grid-3">{cards.map(([t,b])=><div className="card" key={t}><div className="icon">✓</div><h3>{t}</h3><p>{b}</p></div>)}</div></div></section>}

export function WhyChoose(){return <section className="section white"><div className="container split"><div><p className="eyebrow">Why Choose Us</p><h2 style={{fontSize:"43px",letterSpacing:"-.055em",lineHeight:"1.05",margin:"0 0 14px"}}>Clear instructions, flexible service, and a professional appointment from start to finish.</h2><p className="lead">A notary appointment should not feel confusing. We give clients the information they need before booking so the appointment can move quickly and avoid unnecessary delays.</p></div><div className="feature-list"><div className="feature"><strong>Mobile appointments at approved DFW locations</strong>We help clients who need convenient appointments at homes, offices, facilities, and approved public places.</div><div className="feature"><strong>Secure online notarization</strong>Eligible Texas documents may be notarized online through a secure platform.</div><div className="feature"><strong>Accepted ID and credible witness guidance</strong>We help clients understand what to bring before the appointment.</div><div className="feature"><strong>Simple call, text, and online booking</strong>Fast contact options are available throughout the website.</div></div></div></section>}

export function PricingCards(){const cards=[["Traditional Notary","Texas regulated fees","For clients who only need the notarial act completed and can meet locally or use an approved appointment option."],["Mobile Notary","Travel fee + notary fee","For clients who need a notary to travel to an approved location in the Dallas-Fort Worth area."],["Online Notary","$25 session + $10 signature","For eligible Texas documents completed through a secure online notary session."]];return <section className="section" id="pricing"><div className="container"><div className="section-head"><p className="eyebrow">Pricing</p><h2>Simple, transparent pricing.</h2><p>Notary fees, online session fees, travel, urgency, parking, waiting time, and add-ons may affect the final total. We confirm pricing before service.</p></div><div className="grid-3">{cards.map(([t,p,b])=><div className="card" key={t}><h3>{t}</h3><div className="price">{p}</div><p>{b}</p></div>)}</div></div></section>}

export function CommonDocuments(){const docs=["Power of Attorney","Affidavits","Child Travel Consent","Vehicle Title Forms","Business Documents","Medical Forms","School Forms","Real Estate Documents","Statements & Jurats","Acknowledgments","Apartment Forms","General Forms"];return <section className="section white"><div className="container"><div className="section-head"><p className="eyebrow">Common Documents</p><h2>Documents we commonly assist with.</h2><p>Your document should be complete before the appointment, and the signer must be present with acceptable ID.</p></div><div className="pill-grid">{docs.map(d=><div className="pill" key={d}>✓ {d}</div>)}</div></div></section>}

export function ToolsSection(){return <section className="section"><div className="container"><div className="section-head"><p className="eyebrow">Helpful Tools</p><h2>Check your document, ID, and estimate before booking.</h2><p>Use these tools to prepare for your appointment. Final approval depends on the signer, document, ID, appointment type, and applicable notary requirements.</p></div><div className="grid-3"><AcceptedIdChecker/><QuoteCalculator/><NotaryChecker/></div></div></section>}

export function AcceptedIdPreview(){const ids=["Current driver license or state ID","U.S. passport or passport card","Military ID or approved government ID","Signer must personally appear","Signer must be willing and aware","Credible witness may be possible if requirements are met"];return <section className="section dark"><div className="container"><div className="section-head"><p className="eyebrow">Accepted ID</p><h2>Know what to bring before your appointment.</h2><p>Every signer must be properly identified before notarization can be completed.</p></div><div className="grid-3">{ids.map(i=><div className="card" key={i}>✓ {i}</div>)}</div></div></section>}

export function AddOns(){const items=["Printing services","Scan backs","Document delivery","Witness coordination when permitted","After-hours appointments","Expedited appointments","Hospital visits","Nursing facility visits","Jail visits","Business appointments","Apartment community appointments","Real estate document support"];return <section className="section white"><div className="container"><div className="section-head"><p className="eyebrow">Add-On Services</p><h2>Additional services when your appointment needs more support.</h2><p>Some appointments need extra support. Add-on services may be available depending on the document, location, schedule, and appointment type.</p></div><div className="pill-grid">{items.map(i=><div className="pill" key={i}>✓ {i}</div>)}</div></div></section>}

export function FAQBlock(){const faqs=[["Can you explain or prepare my document?","No. We are not attorneys and cannot provide legal advice, prepare legal documents, select forms, or choose the notarial act for you."],["Do I need valid ID?","Yes. Every signer must personally appear and present acceptable identification."],["Do you offer online notarization?","Yes. Remote online notarization is available for eligible Texas documents through a secure online platform."],["Do you travel?","Yes. Mobile appointments are available across Dallas-Fort Worth. Travel fees may apply and are confirmed before service."],["Can I book same day?","Same-day appointments may be available based on schedule, location, and document readiness."],["What if my ID is expired?","An expired ID may not be enough by itself. A credible witness may be possible when requirements are met."]];return <section className="section white"><div className="container"><div className="section-head"><p className="eyebrow">FAQ</p><h2>Questions before booking.</h2><p>Clear answers help you choose the right service and avoid delays at the appointment.</p></div><div className="grid-2">{faqs.map(([q,a])=><div className="card" key={q}><h3>{q}</h3><p>{a}</p></div>)}</div></div></section>}

export function ServiceAreas(){const cities=["Dallas","Irving","Fort Worth","Arlington","Plano","Grand Prairie","Mesquite","Garland","Richardson","Duncanville","Carrollton","Farmers Branch"];return <section className="section"><div className="container"><div className="section-head"><p className="eyebrow">Service Areas</p><h2>Mobile notary service across Dallas-Fort Worth.</h2><p>Travel availability depends on schedule, distance, urgency, and appointment type. Online notarization is available statewide for eligible Texas documents.</p></div><div className="pill-grid">{cities.map(c=><div className="pill" key={c}>Mobile Notary {c}</div>)}</div></div></section>}

export function CTA(){return <section className="section"><div className="container"><div className="card" style={{textAlign:"center",padding:"44px"}}><p className="eyebrow">Ready to schedule?</p><h2 style={{fontSize:"40px",letterSpacing:"-.05em",margin:"0 0 12px"}}>Call now or book your appointment online.</h2><p>A Mobile Notary Service serves Dallas-Fort Worth in person and eligible Texas documents online.</p><div className="hero-actions" style={{justifyContent:"center"}}><a className="btn btn-primary" href="tel:+12144715358">Call Now</a><a className="btn btn-cyan" href={bookingLink}>Book Appointment</a></div></div></div></section>}
